#pragma config(Sensor, S1,     colorS,         sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     leftS,          sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     rightS,         sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor,  motorA,          manipMotor,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,          liftMotor,     tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../includes/math.h"
#include "../includes/hitechnic-colour-v2.h"
tHTCS2 s;

task main() {
    initSensor(&s, S1);
	float hitechVals[6];
	for(int i = 0; i < 3; i++) {
		hitechVals[i] = 1000;
	}

	for(int i = 3; i < 6; i++) {
		hitechVals[i] = 0;
	}

	float hsvHitech[3];
	setMotorBrakeMode(motorB, motorCoast);
	setMotorBrakeMode(motorC, motorCoast);
	clearTimer(T1);
	while (time1[T1] < 5000) {
		readSensor(&s);
		hsvHitech[0] = s.hue;
		hsvHitech[1] = s.saturation;
		hsvHitech[2] = s.value;
		for(int i = 0; i < 3; i++){
			hitechVals[i] = min(hsvHitech[i], hitechVals[i]);
			hitechVals[3 + i] = max(hsvHitech[i], hitechVals[3 + i]);
    }
	}
	float hmin = hitechVals[0];
	float smin = hitechVals[1];
	float vmin = hitechVals[2];
	float hmax = hitechVals[3];
	float smax = hitechVals[4];
	float vmax = hitechVals[5];

	displayBigStringAt(0, 120, "hmin %.4f", hmin);
	displayBigStringAt(0, 100, "smin %.4f", smin);
    displayBigStringAt(0, 80, "vmin %.4f", vmin);
    displayBigStringAt(0, 60, "hmax %.4f", hmax);
    displayBigStringAt(0, 40, "smax %.4f", smax);
    displayBigStringAt(0, 20, "vmax %.4f", vmax);
	waitForButtonPress();
}
